name: Node CI
on:
  push:
    branches:
      - github
  pull_request:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Unit Testing
        run: npm run test
      - name: Test Coverage
        run: npm run test:coverage